//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bidme.Dominio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidadeNegociacao
    {
        public int Id { get; set; }
        public System.DateTime DataValidade { get; set; }
        public int ValidadeDias { get; set; }
        public System.DateTime DataInicio { get; set; }
    
        public virtual Negociacao Negociacao { get; set; }
    }
}
